using Microsoft.CodeAnalysis;

namespace RandomMemory.SourceGenerator;

readonly record struct RandomMemoryGeneratorOptions(string? Namespace, string PrefixClassName, bool IsReturnNullIfKeyNotFound)
{
    public static RandomMemoryGeneratorOptions FromAttribute(AttributeData attributeData)
    {
        var args = attributeData.NamedArguments;

        var ns = args.FirstOrDefault(x => x.Key == nameof(Namespace)).Value.Value as string ?? null;
        var prefix = args.FirstOrDefault(x => x.Key == nameof(PrefixClassName)).Value.Value as string ?? "";
        var isReturnNull = args.FirstOrDefault(x => x.Key == nameof(IsReturnNullIfKeyNotFound)).Value.Value as bool? ?? null;

        return new RandomMemoryGeneratorOptions(ns, prefix, isReturnNull ?? false);
    }

    public static void EmitAttribute(IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource("RandomMemory.RandomMemoryGeneratorOptions.g.cs", """
// <auto-generated />
#pragma warning disable
#nullable enable

using System;

namespace RandomMemory
{
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = false, Inherited = false)]
    internal sealed class RandomMemoryGeneratorOptionsAttribute : Attribute
    {
        public string? Namespace { get; set; } = null;
        public string PrefixClassName { get; set; } = "";
        public bool IsReturnNullIfKeyNotFound { get; set; } = false;
    }
}
""");
    }
}
